
app:
  image: chandankumarbv/blogitaway:staging
  links:
    - db:db
  ports:
    - 9999:8080

db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=password
  volumes:
    - /Users/cbv/work/CMAD/mysql/data:/var/lib/mysql/data
